### ISSUE TITLE
Postgresql embedded tries to extract twice

### ISSUE THREAD

**Issue by isaachazan** [yandex-qatools/postgresql-embedded#8] opened 2015-07-05 13:40 UTC
I am trying to run a unit test on windows that uses postgresql-embedded version 1.3 . 
I use the following code:
```java
PostgresStarter<PostgresExecutable, PostgresProcess> runtime = PostgresStarter.getDefaultInstance();
        final PostgresConfig config = new PostgresConfig(PRODUCTION, new AbstractPostgresConfig.Net(
                "localhost", 30000
        ), new AbstractPostgresConfig.Storage("test"), new AbstractPostgresConfig.Timeout(),
                new AbstractPostgresConfig.Credentials("user", "password"));
        PostgresExecutable exec = runtime.prepare(config);
        process = exec.start();
        String url = String.format("jdbc:postgresql://%s:%s/%s?user=%s&password=%s",
                config.net().host(),
                config.net().port(),
                config.storage().dbName(),
                config.credentials().username(),
                config.credentials().password()
        );
        conn = DriverManager.getConnection(url);
```

It fails with the following:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Extract C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
Extract C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
[postgres error]FATAL:  lock file "postmaster.pid" already exists
[postgres error] HINT:  Is another postgres (PID 9364) running in data directory "C:/Users/ihazan/AppData/Local/Temp/embedpostgres-db-7ffc9f37-858b-4db4-bb5a-c5c5bedecf22"?
[postgres error] 
Extract C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
```

While troubleshooting, i realized that for some reason postgres is being extracted twice instead of once. I confirmed that by putting a breakpoint in the PostgresArtifactStore::extract function and it hits the breakpoint twice. Isn't that a problem. I am also seeing many postgres folders being created in the same run in the temp folder.
The breakpoint is hit once in the call stack of runtime.prepare(config) and another time in the call stack of exec.start().

Thx a lot for any help.

**Comment by smecsia** [comment] 2015-07-06 14:37
Are you trying to launch Postgres as a user with admin privileges? If so, then it is a duplicate of #5 
Please try to launch Postgres server manually from archive: `C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip`

**Comment by isaachazan** [comment] 2015-07-06 16:59
I don't think i am trying to launch it with admin privileges. How do i know with which privileges i am trying to launch it?

**Comment by alexeigit** [comment] 2015-07-27 09:34
Have the same problem on mac os, started embedded postgres in junit like in your github example.

**Comment by bobdenardd** [comment] 2015-08-19 03:43
The fact that it extracts twice is actually misleading. I had a real pain in the ass to debug this issue but it all comes don't to a freaking hardcoded timeout. Have a look at AbstractPostgresConfig class, you will see a constructor for the inner Timeout class which sets it to 2000 ms. On windows and probably on mac os this is not enough, so by raising it to 20000 ms instead it will fix the problem.

**Comment by smecsia** [comment] 2015-08-19 10:25
@bobdenardd could you confirm that the example posted by @isaachazan is working on your system with the change of timeout?

**Comment by bobdenardd** [comment] 2015-08-19 10:33
Yes I do confirm it, I have being performing some benchmarking and 20000 ms appears to be a reasonnable timeout for win 64 bits. Anyway the example posted by @isaachazan strictly corresponds to the unit test named TestPostgreStarter, so all you have to do to verify it is change the timeout and run the tests in this project.

**Comment by bobdenardd** [comment] 2015-08-24 03:49
Is there gonna be any new release integrating a patch for this?

**Comment by isaachazan** [comment] 2015-08-24 09:20
@bobdenardd : how did you re-test it? You changed and then mvn? Did you upload it new version somewhere or are you working with a local repository? Thx.

**Comment by bobdenardd** [comment] 2015-08-24 09:46
So basically what I did was very simple, I changed the timeout, then rebuilt the artifact and installed it in my local repo making sure I had the correct version (in my case I used 1.3, so I just crappily changed the version in embedded postgresql pom to 1.3, works like a charm...). Then in order to use it within my team of developpers I just deployed this customized artifact to our nexus so that they don't have to rebuild it once a day.

**Comment by smecsia** [comment] 2015-08-24 10:24
@bobdenardd have you tried something like the code below?
```java
        final PostgresConfig config = new PostgresConfig(PRODUCTION, new AbstractPostgresConfig.Net("localhost", 30000), 
new AbstractPostgresConfig.Storage("test"), 
new AbstractPostgresConfig.Timeout(20000),
new AbstractPostgresConfig.Credentials("user", "password"));
```
Timeout is not actually hardcoded. It just has the default constructor, so according to [AbstractPostgresConfig.java#L160](https://github.com/yandex-qatools/postgresql-embedded/blob/master/src/main/java/ru/yandex/qatools/embed/postgresql/config/AbstractPostgresConfig.java#L160) you can change it.

**Comment by bobdenardd** [comment] 2015-08-24 10:34
@smecsia Yep it works with the above provided code. The thing is I don't directly use it in my project, as it is used as a deep dependency for unit testing through spring boot. As I didn't want to dig into several plugins, I just modified the default timeout and it did the trick. 

So I acknowledge that it is not an issue on your side since there is a setter and custom constructor for bypassing the default timeout value. My comment was only instructive for those who were wondering why it didn't work "out of the box" on windows environment.

**Comment by isaachazan** [comment] 2015-08-24 11:17
Even when using the above timeout, this is what i am getting:

```bash
2015-08-24 14:12:52,598 DEBUG  [AbstractBeanFactory] (main:) Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor' 
Extract C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
Extract C:\Users\ihazan\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
[postgres error]LOG:  database system was shut down at 2015-08-24 14:13:24 IDT
[postgres error] LOG:  database system is ready to accept connections
[postgres error] LOG:  autovacuum launcher started
[postgres error] 
```

**Comment by bobdenardd** [comment] 2015-08-24 11:19
@isaachazan actually those are misleading log messages. they appear as errors, but they mean your postgre is actually ready, so you may try to connect to it and you will see it is up and running. I get the exact same log messages but it works fine.

**Comment by isaachazan** [comment] 2015-08-25 09:34
Have you guys succeed to to your instance via a psql like client, when i try with the credentials i provided in the PostgresConfig constructor it does not recognize the user. Any idea?

**Comment by bobdenardd** [comment] 2015-08-25 12:20
Works fine for me, able to connect to the DB with the provided users in PostresConfig

**Comment by smecsia** [comment] 2016-03-16 09:22
Outdated.

**Closed by smecsia** 2016-03-16 09:22 UTC
Labels: windows
